---
sidebar: sidebar 
permalink: learn-builders.html 
keywords: software builders, development, benefits 
summary: NetApp Workload Factory for Builders 是一款面向软件构建者的快速构建环境创建工具。 
---
= 了解NetApp Workload Factory for Builders
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Builders 是一款面向软件构建者的快速构建环境创建工具。它可以快速设置个人开发环境，节省时间并为开发人员提供自助服务，同时使 DevOps 团队能够保留对基础设施的控制。使用 Builders，软件开发人员可以快速创建工作区，而无需专门的数据存储或了解开发基础设施。



== NetApp Workload Factory for Builders 是什么？

NetApp Workload Factory for Builders 旨在简化开发人员管理和与不同版本软件交互的方式。  Builders 与 Perforce Helix Core 无缝集成，提供软件版本的即时克隆，为开发、QA 和 CI/CD 流程创建可立即使用的办公空间。

借助"构建者"、您可以轻松创建项目并分配代表您的软件环境及其项目的卷。在更新软件时、您可以为卷创建快照、从而捕获软件在该时刻的状态。这意味着您可以即时访问任何版本的软件、而无需与版本控制系统重新同步、从而节省宝贵的时间和资源。

通过利用ONTAP的快照和克隆功能、构建者可以改进您的开发工作流、从而快速访问多个版本的软件、缩短开发周期并缩短上市时间。

有关 Workload Factory 的更多信息，请参阅link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["工作负载工厂概述"^]。



== NetApp Workload Factory for Builders 功能

NetApp Workload Factory for Builders 提供以下功能：

* 创建、编辑和删除项目
* 为定义的软件版本创建快照
* 创建和删除工作空间(基于克隆)
* 创建访问策略以控制对项目的访问
* 分析每个项目的容量使用情况
* 控制每个项目的克隆大小限制和克隆保留
* 与Perforce等版本控制系统集成




== 构建者中的项目和工作空间

使用"构建程序"时、您需要创建一个项目并分配一个卷来表示您的软件环境及其项目。每次创建新版本的软件时、您都需要重新同步卷数据并创建一个项目快照、以便将卷状态标记为已知版本。项目源卷可能会进行滚动更新、并具有多个快照来标记多个版本。您可以立即将每个快照用作即时克隆、开发人员、QA或构建流程可使用的专用或共享可编辑存储库。特定软件版本环境中的克隆是一个工作空间。



== 工作负载工厂中的操作模式

三种不同的操作模式 - _基本_、_只读_和_读/写_ - 为工作负载工厂内部和外部的部署提供了灵活的选项。使用可在 Workload Factory 外部使用的代码片段，在基本模式下以零信任获得直接价值。在_只读_和_读/写_模式下通过增量信任获取增量值。

详细了解link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["工作负载工厂中的操作模式"^] 。



== 使用 Workload Factory Codebox 实现自动化

Workload Factory通过_Codebox_引入了内置自动化功能。CodeBox具有以下自动化优势：

* *代码段生成*：基础架构即代码(IAC)代码段是在资源创建期间生成的、用于与现有业务流程无缝集成。
* *基础设施即代码副驾驶*：Codebox 是一个基础设施即代码 (IaC) 副驾驶，可帮助开发人员和 DevOps 生成代码来执行 Workload Factory 支持的任何操作。
* *代码查看器和自动化目录*：代码盒提供用于快速分析自动化的代码查看器和用于快速未来重复使用的自动化目录。




== 成本

使用 Workload Factory 的 Builders 功能无需任何费用。



== 许可

无需获得NetApp的特殊许可即可使用 Workload Factory 的 Builders 功能。



== 区域

在支持FSx for ONTAP的所有商业区域中、均支持构建程序。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的 Amazon 地区。"^]

不支持以下AWS区域：

* 中国地区
* GovCloud (美国)地区
* 机密云
* 云的绝密




== 获取帮助

适用于NetApp ONTAP 的Amazon FSX是AWS第一方解决方案。如有与您的FSx for ONTAP文件系统、基础架构或使用此服务的任何解决方案相关的问题或技术支持问题、请使用AWS管理控制台中的支持中心创建AWS支持案例。选择 "FSX for ONTAP " 服务和相应的类别。提供创建 AWS 支持案例所需的其余信息。

有关 Workload Factory 或 Workload Factory 应用程序和服务的一般问题，请参阅link:get-help-builders.html["获取 Workload Factory Builders 的帮助"]。
