---
settings:
  name: Builders workloads
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: 构建者工作负载文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 已知限制
      url: "/known-limitations.html"
  - title: 开始使用
    entries:
    - title: 了解适用于构建者的BlueXP  工作负载工厂
      url: "/learn-builders.html"
    - title: 快速入门
      url: "/quick-start-builders.html"
    - title: 要求
      url: "/requirements-builders.html"
    - title: 将构建者与Perforce集成
      url: "/integrate-perforce.html"
  - title: 使用构建者工作负载
    entries:
    - title: 管理项目
      url: "/manage-projects.html"
    - title: 保护项目
      url: "/protect-projects.html"
    - title: 创建工作空间
      url: "/create-workspaces.html"
    - title: 使用CodeBox实现自动化
      url: "/automate-codebox.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/support-registration.html"
    - title: 获取帮助
      url: "/get-help-builders.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
