---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, Workload Factory, builders, Workload Factory' 
summary: 了解数据库工作负载工厂的新功能。 
---
= NetApp Workload Factory for Builders 的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解 Workload Factory 的 Builders 功能的新功能。



== 2025年10月5日



=== BlueXP workload factory现为NetApp工作负载工厂

BlueXP已重命名并重新设计，以更好地反映其在管理数据基础设施中的作用。因此， BlueXP workload factory已重命名为NetApp工作负载工厂。



== 2025年6月16日



=== 克隆支持

您现在可以在BlueXP Workload Factory for Builders 中克隆一个项目。当您克隆一个项目时，Builders 会从快照创建一个新项目，其配置与原始项目相同。克隆对于快速创建类似项目或用于测试目的很有用。您可以按照 Builders 中的说明安装新的项目克隆。

https://docs.netapp.com/us-en/workload-builders/version-projects.html["管理BlueXP Workload Factory for Builders 项目的版本"]



== 2025年5月4日



=== 更新了权限术语

Workload Factory 用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



== 2024年12月1日



=== 构建者工作负载初始版本

BlueXP Workload Factory for Builders 简化了软件版本的使用和访问，无需自定义工具或脚本。它使您能够将软件版本作为与 Perforce Helix Core 集成的即时克隆来使用，作为开发过程的便捷工作区，从而节省时间和资源。

初始版本包括管理项目和工作空间以及使用CodeBox自动执行操作的功能。您还可以将"构建者"与Perforce Helix Core集成、以便管理每个项目的不同版本并在它们之间快速切换。
